model:
  ndim: 525
  nwell: 2
  num_steps: 1000
  scaling: 10
  beta_min: 1.e-5
  beta_max: 1.e-2
  hidden_size: 2048
  hidden_layers: 12
  emb_size: 10

train:
  batch_size: 256
  num_epoch: 10001
  decay_steps: 1000
  if_norm: True
  lr: 2.e-4

dataset:
  name: CGN
  MC: MC-CGN
SMC:
  n_steps: 15000
  ode_steps: 20
  mc: 50000
  nmc: 2
  n_replicas: 4000
  Kmax_x: 100
  Kmax_eps: 100
  Kmin_x: 2
  Kmin_eps: 2
  compress_exp_x: 0.05
  compress_exp_eps: 0.05
  beta_cut: 0.01



