model:
  ndim: 10
  nwell: 2
  num_steps: 1000
  scaling: 6
  beta_min: 1.e-5
  beta_max: 1.e-2
  hidden_size: 50
  hidden_layers: 1
  emb_size: 10

train:
  batch_size: 128
  num_epoch: 81
  decay_steps: 20
  if_norm: False
  lr: 2.e-4

dataset:
  name: GMM
  MC: 

SMC:
  n_steps: 2000
  ode_steps: 20
  mc: 50000
  nmc: 2
  n_replicas: 1000
  Kmax_x: 10
  Kmax_eps: 10
  Kmin_x: 1
  Kmin_eps: 1
  compress_exp_x: 0.05
  compress_exp_eps: 0.05
  beta_cut: 0.0



